### ISSUE TITLE
"Base schema exists but missing which project it belongs to"

### ISSUE THREAD

**Issue by Konan1236** [MerginMaps/mergin-db-sync#51] opened 2021-08-24 14:12 UTC
I'm trying to set up the connection, I've been able to troubleshoot myself so far but now I get above error message. 
What does this error message entail? It's unclear to me what the 'project' is, it's referring to.

**Comment by Konan1236** [comment] 2021-08-25 13:36
So the problem is within the DB_SCHEMA_MODIFIED and DB_SCHEMA_BASE I'm assuming. What should I do if I do not want to create new schema's but want to just update an existing table within my public schema based on a GeoPackage that's already active within Input/Mergin?

**Comment by lucalanteri** [comment] 2022-06-16 08:34
Hi. I have the same problem, I can't configure an existing schema to start with. I saw that the issue was labeled as bug. If it helps I could do some test.

**Comment by wonder-sk** [comment] 2022-06-16 08:57
Assuming that you have your database tables in a schema, let's call it "my_data", then this is the value you should use for DB_SCHEMA_MODIFIED. The value for DB_SCHEMA_BASE should be a new schema name that db-sync will create and maintain by itself (to keep the sync working correctly). You could call it e.g. "my_data_db_sync_internal":
- DB_SCHEMA_MODIFIED=my_data
- DB_SCHEMA_BASE=my_data_db_sync_internal

Does that make sense? (sorry the naming is somehow confusing)

**Comment by wonder-sk** [comment] 2022-06-16 11:58
Your base schema should _not_ exist at the time you initialize db sync - when you delete it, things should work... (and after the init you should not modify anything in the "base" schema as it would break the sync mechanism).

**Comment by lucalanteri** [comment] 2022-06-16 12:11
I've created the schema by hand because I've this previous error

  File "/mergin-db-sync/dbsync.py", line 257, in _set_db_project_comment
    cur.execute(query.as_string(conn), (json.dumps(comment), ))
psycopg2.errors.InvalidSchemaName: schema "base" does not exist

**Comment by lucalanteri** [comment] 2022-06-16 12:24
Problem seem partially to due to starting data. If I change my real table with a very simple test table the base schema was created successfully, but this error remains [0] .

I also hav this comment for the base schema {"name": "admin/ha", "version": "v0", "error": "Initialization of db-sync failed due to a bug in geodiff"}

[0]
  File "dbsync_daemon.py", line 65, in <module>
    main()
  File "dbsync_daemon.py", line 37, in main
    dbsync.dbsync_init(mc, from_gpkg=False)
  File "/mergin-db-sync/dbsync.py", line 522, in dbsync_init
    changes_gpkg_base = _compare_datasets("sqlite", "", gpkg_full_path, config.db_driver,
  File "/mergin-db-sync/dbsync.py", line 211, in _compare_datasets
    _geodiff_create_changeset_dr(src_driver, src_conn_info, src, dst_driver, dst_conn_info, dst, tmp_changeset)
  File "/mergin-db-sync/dbsync.py", line 203, in _geodiff_create_changeset_dr
    _run_geodiff([config.geodiff_exe, "diff", "--driver-1", src_driver, src_conn_info, "--driver-2", dst_driver, dst_conn_info, src, dst, changeset])
  File "/mergin-db-sync/dbsync.py", line 153, in _run_geodiff
    raise DbSyncError("geodiff failed!\n" + str(cmd))
dbsync.DbSyncError: geodiff failed!
['/geodiff/build/geodiff', 'diff', '--driver-1', 'sqlite', '', '--driver-2', 'postgres', '****', '/tmp/dbsync/ha.gpkg', 'base', '/tmp/clTQBxZY']

**Comment by lucalanteri** [comment] 2022-06-16 12:34
Ok. The last problem was resolved by add some data to the test table. So the main problem remain my real data (may be some void table ?).

**Comment by wonder-sk** [comment] 2022-06-17 13:54
@lucalanteri That's strange that the copy failed when you had zero rows :thinking:  ...would it be possible to provide a dump of your schema in Postgres in the state when it causes the error during db-sync init? I'd like to see if we can find the cause (and fix it). If your dump is sensitive, please feel free to send it by email: `martin.dobias at lutraconsulting.co.uk`

If I can replicate the bugs, I would raise tickets as needed (in db-sync repo or in geodiff repo).

**Comment by lucalanteri** [comment] 2022-06-28 14:55
Hi Martin, after some other tests it seems that changing data type from numeric(10,2) to real resolve also the problem of void table.
Thanks and sorry for the noise

**Comment by jreinier** [comment] 2022-12-08 16:36
I'm experiencing similar issue as above:  trying to initialize from db but get this error...

Status: Downloaded newer image for lutraconsulting/mergin-db-sync:latest
== starting mergin-db-sync daemon == version 1.1.2 ==
Logging in to Mergin...
Processing Mergin Maps project 'Cleveland-Metroparks/nr_test'
Connecting to the database...
Downloading latest Mergin Maps project Cleveland-Metroparks/nr_test to /tmp/dbsync/nr_test
Traceback (most recent call last):
  File "dbsync_daemon.py", line 63, in <module>
    main()
  File "dbsync_daemon.py", line 35, in main
    dbsync.dbsync_init(mc, from_gpkg=False)
  File "/mergin-db-sync/dbsync.py", line 666, in dbsync_init
    init(conn, mc, from_gpkg)
  File "/mergin-db-sync/dbsync.py", line 625, in init
    raise DbSyncError(f"The output GPKG exists but the base schema is missing: {conn_cfg.base}")
dbsync.DbSyncError: The output GPKG exists but the base schema is missing: sync_base


But when I create the base schema (and add {"name": "admin/db-sync", "version": "v0"} comment to the schema)  and try to initialize, I get the following:

Status: Downloaded newer image for lutraconsulting/mergin-db-sync:latest
== starting mergin-db-sync daemon == version 1.1.2 ==
Logging in to Mergin...
Processing Mergin Maps project 'Cleveland-Metroparks/nr_test'
Connecting to the database...
Modified and base schemas already exist
Downloading version v0 of Mergin Maps project Cleveland-Metroparks/nr_test to /tmp/dbsync/nr_test
There are pending changes on server, please run pull command after init
Traceback (most recent call last):
  File "dbsync_daemon.py", line 63, in <module>
    main()
  File "dbsync_daemon.py", line 35, in main
    dbsync.dbsync_init(mc, from_gpkg=False)
  File "/mergin-db-sync/dbsync.py", line 666, in dbsync_init
    init(conn, mc, from_gpkg)
  File "/mergin-db-sync/dbsync.py", line 627, in init
    raise DbSyncError(f"The base schema exists but the output GPKG exists is missing: {gpkg_full_path}")
dbsync.DbSyncError: The base schema exists but the output GPKG exists is missing: /tmp/dbsync/nr_test/cm_wetlands.gpkg

How do I troubleshoot this last problem?

**Closed** 2023-03-24 15:38 UTC
Labels: bug
