### ISSUE TITLE
Add support for MSSQL

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mergin-db-sync#126] opened 2023-08-07 10:18 UTC
So, data can be synced between MM and an MSSQL DB.

**Comment by wonder-sk** [comment] 2023-08-07 11:25
Duplicate of #74

**Closed by wonder-sk** 2023-08-07 11:25 UTC
Labels: enhancement

**Comment by saberraz** [comment] 2023-08-07 12:10
I was sure there was a ticket but nothing was returned when I searched for _mssql_ :man_facepalming:
